  
apiVersion: v1
kind: Service
metadata:
  name: tzankoswebpage-service
  namespace: tzankoswebpage
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: tzankoswebpage