apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  namespace: {{ name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: {{ name }}
  template:
    metadata:
      labels:
        k8s-app: {{ name }}
      name: {{ name }}
    spec:
      containers:
      - name: {{ name }}
        image: {{ registry }}/{{ name }}:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      restartPolicy: Always