apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-service
  namespace: {{ name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: {{ name }}